### ISSUE TITLE
Create .pkgmeta for building

### ISSUE THREAD

**Issue by scottsdevelopment** [LiuCJonathan/HealCommClassic#13]
Instead of bundling libraries together, I strongly recommend the usage of a pkgmeta file,
https://authors.curseforge.com/knowledge-base/projects/527-preparing-the-packagemeta-file

As of today, the updated bundled LibHealComm-4.0 (https://github.com/Azilroka/LibHealComm-4.0) is out of date, and this would be so much easier to handle if we allowed the distributors CI to create the release package.

An example of one can be found here: https://github.com/Aviana/LunaUnitFrames/blob/master/.pkgmeta although this is slightly out of date so I recommend verifying each similar libraries repository.

**Comment by LiuJonathan** [comment]
Issue has been resolved. 
Project now uses an auto packager.
