### ISSUE TITLE
Predictive status text doesn't work unless Blizzard Raid Profile is configured

### ISSUE THREAD

**Issue by scottsdevelopment** [LiuCJonathan/HealCommClassic#14]
I believe if someone has the option enabled, they will understand that they will be using the hooked status text function.

While the feature says it replaces the status text option, the behavior only enables if the raid profile is set to 'Health Lost', I believe it makes more sense to have this checkbox be the setting override as the description implies. I had a non-technical raider test the feature out while sorting out guild heal comms issues and it was not very clear how it was described to be working.

**Comment by LiuJonathan** [comment]
I'll reword the options to make it more clear, however the current behavior needs to stay for people who want different Health display options for each profile.

**Comment by LiuJonathan** [comment]
The option has been reworded in the next update I plan to make another improvement later
