### ISSUE TITLE
Alpha value of Settings.Color

### ISSUE THREAD

**Issue by ioiooi** [LiuCJonathan/HealCommClassic#3]
Hi,

[the alpha value for the statusbar is set to 60](https://github.com/LiuCJonathan/HealCommClassic/blob/1d101b0a85e9f3c890fe16bf8301d5cbf635df0d/HealComm.lua#L18). In the now removed libHealCommClassic a value of 0.6 was used. I think as with the[ rgb values something between 0-1](https://wowwiki.fandom.com/wiki/API_StatusBar_SetStatusBarColor) is the way to go.  
60 is just solid and overlays everything else.
  
cheers

**Comment by LiuJonathan** [comment]
Alpha values are divided by 100 before being stored and used. I'll change it back to a 0-1 scale since it's likely more intuitive. If you're not having any issues with overlay transparencies, I'll close this issue.

**Comment by ioiooi** [comment]
TIL

Thanks for looking into it.

**Comment by LiuJonathan** [comment]
The slider values have been changed. It'll be included in the next release.

**Comment by ioiooi** [comment]
Yo, sorry for the back and forth and I don't actually know if it is the alpha value causing this but here is a screenshot of how the incoming heal bar is overlaying everything.

[https://imgur.com/a/b4nro8u](https://imgur.com/a/b4nro8u)

**Comment by LiuJonathan** [comment]
It looks like I gave healcomm the wrong initial alpha values when upgrading versions. Thanks for the report. I'll fix the issue and create a new release. 

For now, you should be able to fix the issue by setting a new alpha.

**Comment by ioiooi** [comment]
I changed the alpha settings directly and by using the slider. It has no visible effect on the raid frames. It does however change the opacity of the player frame ([link](https://imgur.com/a/kZCe5ZB)). Maybe a other addon  interferes with it ¯\_(ツ)_/¯

**Comment by LiuJonathan** [comment]
Ahh. I think I finally understand what you mean. You want to be able to have a solid green bar that also doesn't block the player's name or health text in raid frames.

I think I've identified a potential fix. After I spend some time testing it, I'll create a new release.

**Comment by LiuJonathan** [comment]
I've released an update that fixes this problem. Let me know if you have any further issues related to this problem
